---
apiVersion: v1
kind: Service
metadata:
  name: tb-service
  labels:
    app: tb-service
spec:
  ports:
  - port: 8080
    name: ui
  - port: 1883
    name: mqtt
  - port: 5683
    name: coap
  selector:
    app: tb
  type: LoadBalancer
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tb-budget
spec:
  selector:
    matchLabels:
      app: tb
  minAvailable: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-config
data:
  zookeeper.enabled: "true"
  zookeeper.url: "zk-headless"
  cassandra.url: "cassandra-headless:9042"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: tb
spec:
  serviceName: "tb-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: tb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - tb-service
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: tb
        imagePullPolicy: Always
        image: thingsboard/application:k8stest
        ports:
        - containerPort: 8080
          name: ui
        - containerPort: 1883
          name: mqtt
        - containerPort: 5683
          name: coap
        - containerPort: 9001
          name: rpc
        resources:
          limits:
            cpu: "250m"
            memory: "500Mi"
          requests:
           cpu: "250m"
           memory: "500Mi"
        env:
        - name: ZOOKEEPER_ENABLED
          valueFrom:
            configMapKeyRef:
              name: tb-config
              key: zookeeper.enabled
        - name: ZOOKEEPER_URL
          valueFrom:
            configMapKeyRef:
              name: tb-config
              key: zookeeper.url
        - name : CASSANDRA_URL
          valueFrom:
            configMapKeyRef:
              name: tb-config
              key: cassandra.url
        - name : RPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - sh
        - -c
        - ./run_thingsboard.sh
        livenessProbe:
          httpGet:
            path: /login
            port: ui-port
          initialDelaySeconds: 120
          timeoutSeconds: 10